filegroup(
    name = "server",
    srcs = glob([
        "server/**/*.h",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "internal",
    srcs = glob([
        "internal/**/*.h",
    ]),
    visibility = ["//visibility:public"],
)
