cc_library(
    name = "server",
    hdrs = glob([
        "server/**/*.h",
    ]),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "internal",
    hdrs = glob([
        "internal/**/*.h",
    ]),
    visibility = ["//visibility:public"],
)
